# Generated by Django 3.1.2 on 2020-10-14 17:33

import authentication.utils
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('description', models.TextField()),
                ('quantity', models.IntegerField(default=0, verbose_name='quantity')),
                ('rate', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='rate')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('invoice_number', models.CharField(max_length=50, verbose_name='invoice number')),
                ('vendor_name', models.CharField(max_length=254, verbose_name='vendor name')),
                ('invoice_date', models.DateField(verbose_name='invoice date')),
                ('copy_of_invoice', models.FileField(upload_to=authentication.utils.unique_upload, verbose_name='copy of invoice')),
                ('list_of_item', models.ManyToManyField(to='authentication.Item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_family_members', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
